"use client";
import {useState, useEffect, FormEvent} from 'react';
import logoSvg from '../../public/logo.svg';
import loadingSvg from '../../public/loading4.svg';
import css from "./chat.module.css";
import Image from 'next/image';
import {extractSvgContents} from '../utils/svgExtract';
import {pickRandom} from '../utils/random';

const adjectives = ['cute', 'grumpy', 'happy', 'sad'];
const prompts = [
  'robot',
  'tree (side view)',
  'solar system',
  'stick man',
  'cat',
  'animal face',
  'spaceship',
  'program icon',
  'green frog'
];

const standalonePrompts = [
  'national flag',
  'car'
];

const suggestRandom = () => {
  const weight = standalonePrompts.length / prompts.length;
  if (Math.random() > weight) {
    return `${pickRandom(adjectives)} ${pickRandom(prompts)}`;
  } else {
    return pickRandom(standalonePrompts);
  }
};


export default function Chat () {

  const LoadingSpinner = () => <Image
    priority
    src={loadingSvg}
    alt={'loading'}
  />;
  
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<string[] | null>(null);
  const [topic, setTopic] = useState('');

  useEffect(() => {
    handleRandom();
  }, []);

  const handleRandom = () => {
    setTopic(suggestRandom());
  };

  const handleSubmit = async (e:FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLoading(true);
    
    const response = await fetch(`/api/ai?topic=${topic}`)
    const data = await response.json()
    console.log(data.answer);
    const svgs = extractSvgContents(data.answer, `${topic}. Generated by ChatSVG.`);
    setLoading(false);
    setResult(svgs);
  };

  return <div className={css.main}>
    <Image
      priority
      src={logoSvg}
      alt={'ChatSVG logo, a cute yellow bear, possibly grumpy.'}
    />
    <h1>ChatSVG</h1>

    {process.env.NEXT_PUBLIC_MOCK_AI ? <p>Dev mode - AI functions are mocked</p> : null}

    {loading ? <LoadingSpinner /> : <div dangerouslySetInnerHTML={{__html: result ?? ''}} />}

    <form onSubmit={handleSubmit}>
      <label>
          SVG topic&nbsp;
          <input type='text' name='topic' value={topic} onChange={e => setTopic(e.currentTarget.value)}></input>
      </label>
      <button type="button" onClick={handleRandom}>Suggest one</button>
      <br />
      <button disabled={loading} className={css.createButton}>Create</button>
    </form>

    {result && <>
      <p>Caution: Results are generated by AI and are therefore unreliable.</p>
      <code className={css.code}>{result}</code>
    </>}

    <p>A quick and dirty side project by <a href='https://solidred.co.uk'>Howard Yeend</a>.</p>

    <p>Improve ChatSVG by <a href='https://github.com/user24/chat-svg'>submitting a PR</a> on github.</p>

    <blockquote className={css.hello}><strong>Hello OS/Twitter folks</strong>. If you have this link it&apos;s because I&apos;ve personally shared it with you as an <strong>early preview</strong>. It&apos;s not ready for the full force of the internet, so I am trusting you not to share it with like reddit or HN just yet, please. However, I do value your individual feedback so please do reach out via whatever medium I sent you this link and let&apos;s talk :)</blockquote>
  </div>;
}